site_name: Django REST - Typed

theme:
  name: "material"
  language: en
  feature:
    tabs: false
  features:
    - navigation.sections
    - toc.integrate
  palette:
    primary: green
    accent: green
  font:
    text: Roboto
    code: Roboto Mono

repo_name: rsinger86/drf-typed
repo_url: https://github.com/rsinger86/drf-typed

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - Introduction: index.md
  - Views:
      - Basic Usage: views/simple_usage.md
      - Advanced Usage: views/advanced_usage.md
      - Pydantic/Marshmallow: views/third_party_schemas.md
      - Request Elements: views/request_elements.md
      - Supported Types: views/supported_types.md
  - Serializers:
      - Typed Serializers: serializers/typed_serializers.md
      - Type-to-Field Refernce: serializers/type_to_field_ref.md
